import os
import time

import pyautogui
screenWidth, screenHeight = pyautogui.size()

print ('STARTING IN 10')
time.sleep(1)
print ('STARTING IN 9')
time.sleep(1)
print ('STARTING IN 8')
time.sleep(1)
print ('STARTING IN 7')
time.sleep(1)
print ('STARTING IN 6')
time.sleep(1)
print ('STARTING IN 5')
time.sleep(1)
print ('STARTING IN 4')
time.sleep(1)
print ('STARTING IN 3')
time.sleep(1)
print ('STARTING IN 2')
time.sleep(1)
print ('STARTING IN 1')
time.sleep(1)
print ('STARTING NOW...')
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('s') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('s') , pyautogui.keyUp('space')
time.sleep(1)
pyautogui.keyDown('a') , pyautogui.keyDown('space')
time.sleep(19)
pyautogui.keyUp('a') , pyautogui.keyUp('space')
time.sleep(1)
print('COMPLETE')